import Head from "next/head";
import PageLayoutDashboard from "../src/components/common/PageLayoutDashboard";
import SideMenu from "../src/components/common/SideMenu";
import StartpageMain from "../src/components/startpage/StartpageMain";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayoutDashboard>
        <SideMenu />
        <StartpageMain />
      </PageLayoutDashboard>
    </div>
  );
}
